# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f378ec0c81309bba37b7a5af036af08a9d4aa056836b5a29aa239e5dcbcfa06e2991a1b5853afc7f27f4cc5238fadab12cdf021fa95109942660a66ad4c9083

test:
  secret_key_base: 1c913ff88977ff956ea9e83e6e6e2a612818299d7c00892b20552e93cb4a2879fc71ad03b9afdccfd17fa6acd3f0d5607d4ff17563db878ce62f401b91d8fb27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
